version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db:/var/lib/postgresql/data

volumes:
  auth_db:
